package ppppp.generate_bean;

import java.util.Date;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.id
     *
     * @mbg.generated Tue Jan 26 11:06:09 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.lastName
     *
     * @mbg.generated Tue Jan 26 11:06:09 CST 2021
     */
    private String lastname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.email
     *
     * @mbg.generated Tue Jan 26 11:06:09 CST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.gender
     *
     * @mbg.generated Tue Jan 26 11:06:09 CST 2021
     */
    private Integer gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.birth
     *
     * @mbg.generated Tue Jan 26 11:06:09 CST 2021
     */
    private Date birth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.login_account
     *
     * @mbg.generated Tue Jan 26 11:06:09 CST 2021
     */
    private String loginAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_employee.departmentid
     *
     * @mbg.generated Tue Jan 26 11:06:09 CST 2021
     */
    private Integer departmentid;

    public Employee(String lastname, String email) {
        this.lastname = lastname;
        this.email = email;
    }

    public Employee() {
    }

    public Employee(Integer id, String lastname, String email, Integer gender, Date birth, String loginAccount, Integer departmentid) {
        this.id = id;
        this.lastname = lastname;
        this.email = email;
        this.gender = gender;
        this.birth = birth;
        this.loginAccount = loginAccount;
        this.departmentid = departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.id
     *
     * @return the value of t_employee.id
     *
     * @mbg.generated Tue Jan 26 11:06:09 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.id
     *
     * @param id the value for t_employee.id
     *
     * @mbg.generated Tue Jan 26 11:06:09 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.lastName
     *
     * @return the value of t_employee.lastName
     *
     * @mbg.generated Tue Jan 26 11:06:09 CST 2021
     */
    public String getLastname() {
        return lastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.lastName
     *
     * @param lastname the value for t_employee.lastName
     *
     * @mbg.generated Tue Jan 26 11:06:09 CST 2021
     */
    public void setLastname(String lastname) {
        this.lastname = lastname == null ? null : lastname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.email
     *
     * @return the value of t_employee.email
     *
     * @mbg.generated Tue Jan 26 11:06:09 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.email
     *
     * @param email the value for t_employee.email
     *
     * @mbg.generated Tue Jan 26 11:06:09 CST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.gender
     *
     * @return the value of t_employee.gender
     *
     * @mbg.generated Tue Jan 26 11:06:09 CST 2021
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.gender
     *
     * @param gender the value for t_employee.gender
     *
     * @mbg.generated Tue Jan 26 11:06:09 CST 2021
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.birth
     *
     * @return the value of t_employee.birth
     *
     * @mbg.generated Tue Jan 26 11:06:09 CST 2021
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.birth
     *
     * @param birth the value for t_employee.birth
     *
     * @mbg.generated Tue Jan 26 11:06:09 CST 2021
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.login_account
     *
     * @return the value of t_employee.login_account
     *
     * @mbg.generated Tue Jan 26 11:06:09 CST 2021
     */
    public String getLoginAccount() {
        return loginAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.login_account
     *
     * @param loginAccount the value for t_employee.login_account
     *
     * @mbg.generated Tue Jan 26 11:06:09 CST 2021
     */
    public void setLoginAccount(String loginAccount) {
        this.loginAccount = loginAccount == null ? null : loginAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_employee.departmentid
     *
     * @return the value of t_employee.departmentid
     *
     * @mbg.generated Tue Jan 26 11:06:09 CST 2021
     */
    public Integer getDepartmentid() {
        return departmentid;
    }

    @Override
    public String toString() {
        return "Employee{" +
                "id=" + id +
                ", lastname='" + lastname + '\'' +
                ", email='" + email + '\'' +
                ", gender=" + gender +
                ", birth=" + birth +
                ", loginAccount='" + loginAccount + '\'' +
                ", departmentid=" + departmentid +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_employee.departmentid
     *
     * @param departmentid the value for t_employee.departmentid
     *
     * @mbg.generated Tue Jan 26 11:06:09 CST 2021
     */
    public void setDepartmentid(Integer departmentid) {
        this.departmentid = departmentid;
    }
}